### ISSUE TITLE
0.60 Update Broke Lighting for Me

### ISSUE THREAD

**Issue by friction1** [Codas/foundryvtt-performance-hacks#11]
Just narrowed it down to this module as to why I could no longer create working light sources on the map in my game. Not sure why this is happening, but it's definitely this module and I believe the latest update broke this.

Foundry 12.331
DND5e 4.0.4

**Comment by Codas** [comment]
Thank you for noticing this and informing me. Vision seems to work fine but lights do not with these changes. I will have to investigate this. For now It's probably best to downgrade to the previous version. I've removed 0.6.0 from the module browser in the meantime..

**Comment by Codas** [comment]
I'm sorry you had to encounter this issue. Version 0.6.1 should fix that issue

**Comment by Codas** [comment]
This should be resolved with 0.6.4. Can you confirm it is working now?

**Comment by friction1** [comment]
Yes confirmed working
