### ISSUE TITLE
French translation done

### ISSUE THREAD

**Issue by Dolgrenn** [Codas/foundryvtt-performance-hacks#3]
[fr.json](https://github.com/user-attachments/files/16274289/fr.json)

Hi, here is the french translation.

**Comment by Codas** [comment]
Thank you!

**Comment by Dolgrenn** [comment]
np 😉
________________________________
De : Arne ***@***.***>
Envoyé : mercredi 17 juillet 2024 22:25
À : Codas/foundryvtt-performance-hacks ***@***.***>
Cc : Dolgrenn ***@***.***>; Author ***@***.***>
Objet : Re: [Codas/foundryvtt-performance-hacks] French translation done (Issue #3)


Thank you!
