### ISSUE TITLE
[Feature] Dorako UX Token Ring Support

### ISSUE THREAD

**Issue by ChasarooniZ** [Codas/foundryvtt-performance-hacks#5]
Is there anyway for this module to add comparability/support for Dorako UI's token effect ring feature?

**Comment by Codas** [comment]
Its already supported. In fact it evolved from my work on making the token rings in dorako ux more performant. Dorako currently uses a shared render texture to effectively make token effect UI drawing even more performant than this module.

Actually, the "cache token effect ui" setting is internally disabled if dorako UX "adjust token effect hud" setting is enabled for this very reason.

**Comment by ChasarooniZ** [comment]
Ah okay, I must have my settings mixed up (I have a few worlds and must have mixed up which one had the setting for the HUD circle enabled)
