### ISSUE TITLE
Bar Brawl conflict

### ISSUE THREAD

**Issue by weepingminotaur** [Codas/foundryvtt-performance-hacks#6]
Getting this yellow conflict warning when running Prime Performance with the Bar Brawl module.
<img width="576" alt="Screenshot 2024-07-22 at 5 52 43 PM" src="https://github.com/user-attachments/assets/dfbfef57-dfb0-42ad-82be-9a1d47f32d82">

**Comment by Codas** [comment]
I was afraid of something like this... I'm not sure there is much I can do, but I'll look into it!

**Comment by Codas** [comment]
Version 0.5.0 should now support bar brawl :)
