### ISSUE TITLE
Prime Performance and Token Variant Art (5e)

### ISSUE THREAD

**Issue by Dyrnwyrm** [Codas/foundryvtt-performance-hacks#8]
I just noticed a really weird bug between prime performance and TVA, seems like PP override a lot of the options of TVA; for example some effects become "ghost effects" on the token when you delete the active effect from it leaving just the icon (this is solved if you drop the token on the canvas again), **another weird interaction that i noticed is that prime performance cancels the "dont show temporary active effects on token" options from TVA.**

Love your module and i hope something can be done about these small incompatibility issues.

Small edit: the second compatibility issue was fixed in a recent TVA release, so only the "ghost effects" are part of the compatibility problems.

**Comment by Codas** [comment]
First of all, thank you for the bug report. That also led me to look into TVA a bit more and looks like it might just be what I need for an upcoming session of mine. Poor players...

Nevertheless, I found the issue and I think the new implementation is more robust either way (unless someone also overrides THAT function...)

Can you maybe try v0.5.4 and report back if all the issues are fixed for you?

**Comment by Dyrnwyrm** [comment]
Sure let me test it, also thanks for the quick fix, i only have TVA as something that handles tokens, it was just a weird visual bug that just confused my players.
